### ISSUE TITLE
AutoPATT.py not working for Spanish output (non-legacy)

### ISSUE THREAD

**Issue by philcombiths** [philcombiths/AutoPATTPy#1]
source_path=r"D:\Data\test\C102_AutoPATT_Post_Spanish.csv"

AutoPATT(source_path, legacy=False)
Traceback (most recent call last):

  File "<ipython-input-5-a08ad784de3c>", line 1, in <module>
    AutoPATT(source_path, legacy=False)

  File "C:\Users\Philip\Documents\github\AutoPATTPy\AutoPATTPy\AutoPATTPy.py", line 102, in __init__
    i_targ = [

ValueError: True is not in list

**Comment by philcombiths** [comment]
May be due to the fact that English has two extra lines before TARGETS:

No targets found after Step One
No targets found after Step Two

**Comment by philcombiths** [comment]
can temp resolve by editing row: TARGET(S) AFTER Step One:  to TARGETS AFTER Step One:

**Comment by philcombiths** [comment]
Resolved in AutoPATT master
